/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab3.database.jooq;


import com.emented.weblab3.database.jooq.tables.Hits;
import com.emented.weblab3.database.jooq.tables.records.HitsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * s336189.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HitsRecord> HITS_PKEY = Internal.createUniqueKey(Hits.HITS, DSL.name("hits_pkey"), new TableField[] { Hits.HITS.ID }, true);
}
