/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab3.database.jooq;


import com.emented.weblab3.database.jooq.tables.Hits;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S336189 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s336189</code>
     */
    public static final S336189 S336189 = new S336189();

    /**
     * The table <code>s336189.hits</code>.
     */
    public final Hits HITS = Hits.HITS;

    /**
     * No further instances allowed
     */
    private S336189() {
        super("s336189", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Hits.HITS
        );
    }
}
