/*
 * This file is generated by jOOQ.
 */
package com.emented.weblab3.database.jooq;


import com.emented.weblab3.database.jooq.tables.Hits;


/**
 * Convenience access to all tables in s336189.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s336189.hits</code>.
     */
    public static final Hits HITS = Hits.HITS;
}
