CREATE TABLE IF NOT EXISTS s336189.hits (
    id SERIAL,
    session_id VARCHAR NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    r DOUBLE PRECISION NOT NULL,
    check_date TIMESTAMP WITH TIME ZONE NOT NULL,
    execution_time BIGINT NOT NULL,
    status BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);